#Mappings for xmlnames/directories

import json

def directorymapping():
    directorymapping = '''
                {
                   "installedPackages":"InstalledPackage",
                   "labels":"CustomLabels",
                   "staticresources":"StaticResource",
                   "scontrols":"Scontrol",
                   "components":"ApexComponent",
                   "pages":"ApexPage",
                   "queues":"Queue",
                   "dataSources":"ExternalDataSource",
                   "roles":"Role",
                   "groups":"Group",
                   "objects":"CustomObject",
                   "reportTypes":"ReportType",
                   "reports":"Report",
                   "dashboards":"Dashboard",
                   "analyticSnapshots":"AnalyticSnapshot",
                   "layouts":"Layout",
                   "weblinks":"CustomPageWebLink",
                   "quickActions":"QuickAction",
                   "flexipages":"FlexiPage",
                   "tabs":"CustomTab",
                   "applications":"CustomApplication",
                   "letterhead":"Letterhead",
                   "email":"EmailTemplate",
                   "flows":"Flow",
                   "workflows":"Workflow",
                   "assignmentRules":"AssignmentRules",
                   "autoResponseRules":"AutoResponseRules",
                   "escalationRules":"EscalationRules",
                   "postTemplates":"PostTemplate",
                   "approvalProcesses":"ApprovalProcess",
                   "homePageComponents":"HomePageComponent",
                   "homePageLayouts":"HomePageLayout",
                   "objectTranslations":"CustomObjectTranslation",
                   "translations":"Translations",
                   "classes":"ApexClass",
                   "triggers":"ApexTrigger",
                   "profiles":"Profile",
                   "permissionsets":"PermissionSet",
                   "datacategorygroups":"DataCategoryGroup",
                   "remoteSiteSettings":"RemoteSiteSetting",
                   "authproviders":"AuthProvider",
                   "sites":"CustomSite",
                   "leadSharingRules":"LeadSharingRules",
                   "campaignSharingRules":"CampaignSharingRules",
                   "caseSharingRules":"CaseSharingRules",
                   "contactSharingRules":"ContactSharingRules",
                   "opportunitySharingRules":"OpportunitySharingRules",
                   "accountSharingRules":"AccountSharingRules",
                   "customObjectSharingRules":"CustomObjectSharingRules",
                   "userSharingRules":"UserSharingRules",
                   "communities":"Community",
                   "callCenters":"CallCenter",
                   "connectedApps":"ConnectedApp",
                   "networks":"Network",
                   "samlssoconfigs":"SamlSsoConfig",
                   "settings":"Settings"
                }
    '''

    return json.loads(directorymapping)


def directorynames():

    directorynames = [
        "installedPackages",
        "labels",
        "staticresources",
        "scontrols",
        "components",
        "pages",
        "queues",
        "dataSources",
        "roles",
        "groups",
        "objects",
        "reportTypes",
        "reports",
        "dashboards",
        "analyticSnapshots",
        "layouts",
        "weblinks",
        "quickActions",
        "flexipages",
        "tabs",
        "applications",
        "letterhead",
        "email",
        "flows",
        "workflows",
        "assignmentRules",
        "autoResponseRules",
        "escalationRules",
        "postTemplates",
        "approvalProcesses",
        "homePageComponents",
        "homePageLayouts",
        "objectTranslations",
        "translations",
        "classes",
        "triggers",
        "profiles",
        "permissionsets",
        "datacategorygroups",
        "remoteSiteSettings",
        "authproviders",
        "sites",
        "leadSharingRules",
        "campaignSharingRules",
        "caseSharingRules",
        "contactSharingRules",
        "opportunitySharingRules",
        "accountSharingRules",
        "customObjectSharingRules",
        "userSharingRules",
        "communities",
        "callCenters",
        "connectedApps",
        "networks",
        "samlssoconfigs",
        "settings"
    ]
    return directorynames

def suffixnames():
    suffixnames = [
        "installedPackage",
        "labels",
        "resource",
        "scf",
        "component",
        "page",
        "queue",
        "dataSource",
        "role",
        "group",
        "object",
        "reportType",
        "report",
        "dashboard",
        "snapshot",
        "layout",
        "weblink",
        "quickAction",
        "flexipage",
        "tab",
        "app",
        "letter",
        "email",
        "flow",
        "workflow",
        "assignmentRules",
        "autoResponseRules",
        "escalationRules",
        "postTemplate",
        "approvalProcess",
        "homePageComponent",
        "homePageLayout",
        "objectTranslation",
        "translation",
        "cls",
        "trigger",
        "profile",
        "permissionset",
        "datacategorygroup",
        "remoteSite",
        "authprovider",
        "site",
        "sharingRules",
        "sharingRules",
        "sharingRules",
        "sharingRules",
        "sharingRules",
        "sharingRules",
        "sharingRules",
        "sharingRules",
        "community",
        "callCenter",
        "connectedApp",
        "network",
        "samlssoconfig",
        "settings"
    ]

    return suffixnames
